name: CI

on:
  pull_request:
    paths:
      - '*.yaml'
      - '.github/workflows/ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }} / ${{ matrix.esphome-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        #### Modify below here to match your project ####
        file:
          - athom-cb02.yaml
          - athom-garage-door.yaml
          - athom-mini-switch.yaml
          - athom-presence-sensor.yaml
          - athom-relay-board-x1.yaml
          - athom-relay-board-x2.yaml
          - athom-relay-board-x4.yaml
          - athom-relay-board-x8.yaml
          - athom-rgb-light.yaml
          - athom-rgbct-light.yaml
          - athom-rgbw-light.yaml
          - athom-rgbww-light.yaml
          - athom-smart-plug-v2.yaml
          - athom-smart-plug.yaml
          - athom-sw01-v2.yaml
          - athom-sw01.yaml
          - athom-sw02-v2.yaml
          - athom-sw02.yaml
          - athom-sw03.yaml
          - athom-sw04.yaml
          - athom-wall-outlet.yaml
          - athom-without-relay-plug.yaml
        #### Modify above here to match your project ####

        esphome-version:
          - stable
          - beta
          - dev
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: ESPHome ${{ matrix.esphome-version }}
        uses: esphome/build-action@v4.0.3
        with:
          yaml-file: ${{ matrix.file }}.yaml
          version: ${{ matrix.esphome-version }}